# Generated by Django 4.0 on 2023-03-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='wathcAgain',
            new_name='watchAgain',
        ),
    ]
